<?php

namespace Modules\Platform\Settings\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Modules\Platform\Core\Helper\SeederHelper;

/**
 * Class CountrySeeder
 * @package Modules\Platform\Settings\Database\Seeders
 */
class CountrySeeder extends SeederHelper
{
    private static $countries = [
        /* ['id' => '1','cod_uic' => '238','cod_iso' => 'AE','name' => 'ABU DHABI'],
        ['id' => '2','cod_uic' => '002','cod_iso' => 'AF','name' => 'AFGHANISTAN'],
        ['id' => '3','cod_uic' => '239','cod_iso' => 'AE','name' => 'AJMAN'],
        ['id' => '4','cod_uic' => '292','cod_iso' => 'AX','name' => 'ALAND ISOLE'],
        ['id' => '5','cod_uic' => '087','cod_iso' => 'AL','name' => 'ALBANIA'],
        ['id' => '6','cod_uic' => '003','cod_iso' => 'DZ','name' => 'ALGERIA'],
        ['id' => '7','cod_uic' => '148','cod_iso' => 'AS','name' => 'AMERICAN SAMOA'],
        ['id' => '8','cod_uic' => '004','cod_iso' => 'AD','name' => 'ANDORRA'],
        ['id' => '9','cod_uic' => '133','cod_iso' => 'AO','name' => 'ANGOLA'],
        ['id' => '10','cod_uic' => '209','cod_iso' => 'AI','name' => 'ANGUILLA'],
        ['id' => '11','cod_uic' => '180','cod_iso' => 'AQ','name' => 'ANTARTIDE'],
        ['id' => '12','cod_uic' => '197','cod_iso' => 'AG','name' => 'ANTIGUA E BARBUDA'],
        ['id' => '13','cod_uic' => '005','cod_iso' => 'SA','name' => 'ARABIA SAUDITA'],
        ['id' => '14','cod_uic' => '006','cod_iso' => 'AR','name' => 'ARGENTINA'],
        ['id' => '15','cod_uic' => '266','cod_iso' => 'AM','name' => 'ARMENIA'],
        ['id' => '16','cod_uic' => '212','cod_iso' => 'AW','name' => 'ARUBA'],
        ['id' => '17','cod_uic' => '227','cod_iso' => 'SH','name' => 'ASCENSION'],
        ['id' => '18','cod_uic' => '007','cod_iso' => 'AU','name' => 'AUSTRALIA'],
        ['id' => '19','cod_uic' => '008','cod_iso' => 'AT','name' => 'AUSTRIA'],
        ['id' => '20','cod_uic' => '268','cod_iso' => 'AZ','name' => 'AZERBAIGIAN'],
        ['id' => '21','cod_uic' => '234','cod_iso' => 'PT','name' => 'AZZORRE ISOLE'],
        ['id' => '22','cod_uic' => '160','cod_iso' => 'BS','name' => 'BAHAMAS'],
        ['id' => '23','cod_uic' => '169','cod_iso' => 'BH','name' => 'BAHRAIN'],
        ['id' => '24','cod_uic' => '130','cod_iso' => 'BD','name' => 'BANGLADESH'],
        ['id' => '25','cod_uic' => '118','cod_iso' => 'BB','name' => 'BARBADOS'],
        ['id' => '26','cod_uic' => '009','cod_iso' => 'BE','name' => 'BELGIO'],
        ['id' => '27','cod_uic' => '198','cod_iso' => 'BZ','name' => 'BELIZE'],
        ['id' => '28','cod_uic' => '158','cod_iso' => 'BJ','name' => 'BENIN'],
        ['id' => '29','cod_uic' => '207','cod_iso' => 'BM','name' => 'BERMUDA'],
        ['id' => '30','cod_uic' => '097','cod_iso' => 'BT','name' => 'BHUTAN'],
        ['id' => '31','cod_uic' => '264','cod_iso' => 'BY','name' => 'BIELORUSSIA'],
        ['id' => '32','cod_uic' => '010','cod_iso' => 'BO','name' => 'BOLIVIA'],
        ['id' => '33','cod_uic' => '295','cod_iso' => 'BQ','name' => 'BONAIRE SAINT EUSTATIUS AND SABA'],
        ['id' => '34','cod_uic' => '274','cod_iso' => 'BA','name' => 'BOSNIA E ERZEGOVINA'],
        ['id' => '35','cod_uic' => '098','cod_iso' => 'BW','name' => 'BOTSWANA'],
        ['id' => '36','cod_uic' => '280','cod_iso' => 'BV','name' => 'BOUVET ISOLA'],
        ['id' => '37','cod_uic' => '011','cod_iso' => 'BR','name' => 'BRASILE'],
        ['id' => '38','cod_uic' => '125','cod_iso' => 'BN','name' => 'BRUNEI DARUSSALAM'],
        ['id' => '39','cod_uic' => '012','cod_iso' => 'BG','name' => 'BULGARIA'],
        ['id' => '40','cod_uic' => '142','cod_iso' => 'BF','name' => 'BURKINA FASO'],
        ['id' => '41','cod_uic' => '025','cod_iso' => 'BI','name' => 'BURUNDI'],
        ['id' => '42','cod_uic' => '135','cod_iso' => 'KH','name' => 'CAMBOGIA'],
        ['id' => '43','cod_uic' => '119','cod_iso' => 'CM','name' => 'CAMEROON'],
        ['id' => '44','cod_uic' => '139','cod_iso' => 'IT','name' => 'CAMPIONE D\'ITALIA'],
        ['id' => '45','cod_uic' => '013','cod_iso' => 'CA','name' => 'CANADA'],
        ['id' => '46','cod_uic' => '100','cod_iso' => 'ES','name' => 'CANARIE ISOLE'],
        ['id' => '47','cod_uic' => '188','cod_iso' => 'CV','name' => 'CAPO VERDE'],
        ['id' => '48','cod_uic' => '256','cod_iso' => 'FM','name' => 'CAROLINE ISOLE'],
        ['id' => '49','cod_uic' => '211','cod_iso' => 'KY','name' => 'CAYMAN ISOLE'],
        ['id' => '50','cod_uic' => '275','cod_iso' => 'CZ','name' => 'CECA (REPUBBLICA)'],
        ['id' => '51','cod_uic' => '143','cod_iso' => 'CF','name' => 'CENTROAFRICANA (REPUBBLICA)'],
        ['id' => '52','cod_uic' => '246','cod_iso' => 'ES','name' => 'CEUTA'],
        ['id' => '53','cod_uic' => '230','cod_iso' => 'ES','name' => 'CHAFARINAS'],
        ['id' => '54','cod_uic' => '255','cod_iso' => 'IO','name' => 'CHAGOS ISOLE'],
        ['id' => '55','cod_uic' => '282','cod_iso' => 'CX','name' => 'CHRISTMAS ISOLA'],
        ['id' => '56','cod_uic' => '144','cod_iso' => 'TD','name' => 'CIAD'],
        ['id' => '57','cod_uic' => '015','cod_iso' => 'CL','name' => 'CILE'],
        ['id' => '58','cod_uic' => '016','cod_iso' => 'CN','name' => 'CINA'],
        ['id' => '59','cod_uic' => '101','cod_iso' => 'CY','name' => 'CIPRO'],
        ['id' => '60','cod_uic' => '223','cod_iso' => 'FR','name' => 'CLIPPERTON'],
        ['id' => '61','cod_uic' => '281','cod_iso' => 'CC','name' => 'COCOS  KEELING ISOLA'],
        ['id' => '62','cod_uic' => '017','cod_iso' => 'CO','name' => 'COLOMBIA'],
        ['id' => '63','cod_uic' => '176','cod_iso' => 'KM','name' => 'COMOROS ISOLE'],
        ['id' => '64','cod_uic' => '145','cod_iso' => 'CG','name' => 'CONGO'],
        ['id' => '65','cod_uic' => '018','cod_iso' => 'CD','name' => 'CONGO R. DEM.'],
        ['id' => '66','cod_uic' => '237','cod_iso' => 'CK','name' => 'COOK ISOLE'],
        ['id' => '67','cod_uic' => '074','cod_iso' => 'KP','name' => 'COREA DEL NORD(REPUB DEMOCR POPOLARE)'],
        ['id' => '68','cod_uic' => '084','cod_iso' => 'KR','name' => 'COREA DEL SUD (REPUBBLICA DI)'],
        ['id' => '69','cod_uic' => '146','cod_iso' => 'CI','name' => 'COSTA D\'AVORIO'],
        ['id' => '70','cod_uic' => '019','cod_iso' => 'CR','name' => 'COSTA RICA'],
        ['id' => '71','cod_uic' => '261','cod_iso' => 'HR','name' => 'CROAZIA'],
        ['id' => '72','cod_uic' => '020','cod_iso' => 'CU','name' => 'CUBA'],
        ['id' => '73','cod_uic' => '296','cod_iso' => 'CW','name' => 'CURACAO'],
        ['id' => '74','cod_uic' => '021','cod_iso' => 'DK','name' => 'DANIMARCA'],
        ['id' => '75','cod_uic' => '192','cod_iso' => 'DM','name' => 'DOMINICA'],
        ['id' => '76','cod_uic' => '063','cod_iso' => 'DO','name' => 'DOMINICANA (REPUBBLICA)'],
        ['id' => '77','cod_uic' => '240','cod_iso' => 'AE','name' => 'DUBAI'],
        ['id' => '78','cod_uic' => '024','cod_iso' => 'EC','name' => 'ECUADOR'],
        ['id' => '79','cod_uic' => '023','cod_iso' => 'EG','name' => 'EGITTO'],
        ['id' => '80','cod_uic' => '064','cod_iso' => 'SV','name' => 'EL SALVADOR'],
        ['id' => '81','cod_uic' => '277','cod_iso' => 'ER','name' => 'ERITREA'],
        ['id' => '82','cod_uic' => '257','cod_iso' => 'EE','name' => 'ESTONIA'],
        ['id' => '83','cod_uic' => '026','cod_iso' => 'ET','name' => 'ETIOPIA'],
        ['id' => '84','cod_uic' => '204','cod_iso' => 'FO','name' => 'FAER OER ISOLE'],
        ['id' => '85','cod_uic' => '190','cod_iso' => 'FK','name' => 'FALKLAND ISOLE'],
        ['id' => '86','cod_uic' => '161','cod_iso' => 'FJ','name' => 'FIJI'],
        ['id' => '87','cod_uic' => '027','cod_iso' => 'PH','name' => 'FILIPPINE'],
        ['id' => '88','cod_uic' => '028','cod_iso' => 'FI','name' => 'FINLANDIA'],
        ['id' => '89','cod_uic' => '029','cod_iso' => 'FR','name' => 'FRANCIA'],
        ['id' => '90','cod_uic' => '241','cod_iso' => 'AE','name' => 'FUIJAYRAH'],
        ['id' => '91','cod_uic' => '157','cod_iso' => 'GA','name' => 'GABON'],
        ['id' => '92','cod_uic' => '164','cod_iso' => 'GM','name' => 'GAMBIA'],
        ['id' => '93','cod_uic' => '267','cod_iso' => 'GE','name' => 'GEORGIA'],
        ['id' => '94','cod_uic' => '094','cod_iso' => 'DE','name' => 'GERMANIA'],
        ['id' => '95','cod_uic' => '112','cod_iso' => 'GH','name' => 'GHANA'],
        ['id' => '96','cod_uic' => '082','cod_iso' => 'JM','name' => 'GIAMAICA'],
        ['id' => '97','cod_uic' => '088','cod_iso' => 'JP','name' => 'GIAPPONE'],
        ['id' => '98','cod_uic' => '102','cod_iso' => 'GI','name' => 'GIBILTERRA'],
        ['id' => '99','cod_uic' => '113','cod_iso' => 'DJ','name' => 'GIBUTI'],
        ['id' => '100','cod_uic' => '122','cod_iso' => 'JO','name' => 'GIORDANIA'],
        ['id' => '101','cod_uic' => '228','cod_iso' => 'SH','name' => 'GOUGH'],
        ['id' => '102','cod_uic' => '032','cod_iso' => 'GR','name' => 'GRECIA'],
        ['id' => '103','cod_uic' => '156','cod_iso' => 'GD','name' => 'GRENADA'],
        ['id' => '104','cod_uic' => '200','cod_iso' => 'GL','name' => 'GROENLANDIA'],
        ['id' => '105','cod_uic' => '214','cod_iso' => 'GP','name' => 'GUADALUPA'],
        ['id' => '106','cod_uic' => '154','cod_iso' => 'GU','name' => 'GUAM'],
        ['id' => '107','cod_uic' => '033','cod_iso' => 'GT','name' => 'GUATEMALA'],
        ['id' => '108','cod_uic' => '201','cod_iso' => 'GG','name' => 'GUERNSEY C.I.'],
        ['id' => '109','cod_uic' => '123','cod_iso' => 'GF','name' => 'GUIANA FRANCESE'],
        ['id' => '110','cod_uic' => '137','cod_iso' => 'GN','name' => 'GUINEA'],
        ['id' => '111','cod_uic' => '185','cod_iso' => 'GW','name' => 'GUINEA BISSAU'],
        ['id' => '112','cod_uic' => '167','cod_iso' => 'GQ','name' => 'GUINEA EQUATORIALE'],
        ['id' => '113','cod_uic' => '159','cod_iso' => 'GY','name' => 'GUYANA'],
        ['id' => '114','cod_uic' => '034','cod_iso' => 'HT','name' => 'HAITI'],
        ['id' => '115','cod_uic' => '284','cod_iso' => 'HM','name' => 'HEARD E MCDONALD ISOLE'],
        ['id' => '116','cod_uic' => '035','cod_iso' => 'HN','name' => 'HONDURAS'],
        ['id' => '117','cod_uic' => '103','cod_iso' => 'HK','name' => 'HONG KONG'],
        ['id' => '118','cod_uic' => '114','cod_iso' => 'IN','name' => 'INDIA'],
        ['id' => '119','cod_uic' => '129','cod_iso' => 'ID','name' => 'INDONESIA'],
        ['id' => '120','cod_uic' => '039','cod_iso' => 'IR','name' => 'IRAN (REPUBBLICA ISLAMICA DI)'],
        ['id' => '121','cod_uic' => '038','cod_iso' => 'IQ','name' => 'IRAQ'],
        ['id' => '122','cod_uic' => '040','cod_iso' => 'IE','name' => 'IRLANDA'],
        ['id' => '123','cod_uic' => '041','cod_iso' => 'IS','name' => 'ISLANDA'],
        ['id' => '124','cod_uic' => '252','cod_iso' => 'UM','name' => 'ISOLE AMERICANE DEL PACIFICO'],
        ['id' => '125','cod_uic' => '182','cod_iso' => 'IL','name' => 'ISRAELE'],
        ['id' => '126','cod_uic' => '086','cod_iso' => 'IT','name' => 'ITALIA'],
        ['id' => '127','cod_uic' => '202','cod_iso' => 'JE','name' => 'JERSEY C.I.'],
        ['id' => '128','cod_uic' => '269','cod_iso' => 'KZ','name' => 'KAZAKISTAN'],
        ['id' => '129','cod_uic' => '116','cod_iso' => 'KE','name' => 'KENYA'],
        ['id' => '130','cod_uic' => '194','cod_iso' => 'KI','name' => 'KIRIBATI'],
        ['id' => '131','cod_uic' => '291','cod_iso' => 'RS','name' => 'KOSOVO'],
        ['id' => '132','cod_uic' => '126','cod_iso' => 'KW','name' => 'KUWAIT'],
        ['id' => '133','cod_uic' => '270','cod_iso' => 'KG','name' => 'KYRGYZSTAN'],
        ['id' => '134','cod_uic' => '136','cod_iso' => 'LA','name' => 'LAOS (REP DEMOCRATICA POP)'],
        ['id' => '135','cod_uic' => '089','cod_iso' => 'LS','name' => 'LESOTHO'],
        ['id' => '136','cod_uic' => '258','cod_iso' => 'LV','name' => 'LETTONIA'],
        ['id' => '137','cod_uic' => '095','cod_iso' => 'LB','name' => 'LIBANO'],
        ['id' => '138','cod_uic' => '044','cod_iso' => 'LR','name' => 'LIBERIA'],
        ['id' => '139','cod_uic' => '045','cod_iso' => 'LY','name' => 'LIBIA'],
        ['id' => '140','cod_uic' => '090','cod_iso' => 'LI','name' => 'LIECHTENSTEIN'],
        ['id' => '141','cod_uic' => '259','cod_iso' => 'LT','name' => 'LITUANIA'],
        ['id' => '142','cod_uic' => '092','cod_iso' => 'LU','name' => 'LUSSEMBURGO'],
        ['id' => '143','cod_uic' => '059','cod_iso' => 'MO','name' => 'MACAO'],
        ['id' => '144','cod_uic' => '278','cod_iso' => 'MK','name' => 'MACEDONIA'],
        ['id' => '145','cod_uic' => '104','cod_iso' => 'MG','name' => 'MADAGASCAR'],
        ['id' => '146','cod_uic' => '235','cod_iso' => 'PT','name' => 'MADEIRA'],
        ['id' => '147','cod_uic' => '056','cod_iso' => 'MW','name' => 'MALAWI'],
        ['id' => '148','cod_uic' => '106','cod_iso' => 'MY','name' => 'MALAYSIA'],
        ['id' => '149','cod_uic' => '127','cod_iso' => 'MV','name' => 'MALDIVE'],
        ['id' => '150','cod_uic' => '149','cod_iso' => 'ML','name' => 'MALI'],
        ['id' => '151','cod_uic' => '105','cod_iso' => 'MT','name' => 'MALTA'],
        ['id' => '152','cod_uic' => '203','cod_iso' => 'IM','name' => 'MAN ISOLA'],
        ['id' => '153','cod_uic' => '219','cod_iso' => 'MP','name' => 'MARIANNE SETTENTRIONALI ISOLE'],
        ['id' => '154','cod_uic' => '107','cod_iso' => 'MA','name' => 'MAROCCO'],
        ['id' => '155','cod_uic' => '217','cod_iso' => 'MH','name' => 'MARSHALL ISOLE'],
        ['id' => '156','cod_uic' => '213','cod_iso' => 'MQ','name' => 'MARTINICA'],
        ['id' => '157','cod_uic' => '141','cod_iso' => 'MR','name' => 'MAURITANIA'],
        ['id' => '158','cod_uic' => '128','cod_iso' => 'MU','name' => 'MAURITIUS ISOLE'],
        ['id' => '159','cod_uic' => '226','cod_iso' => 'YT','name' => 'MAYOTTE'],
        ['id' => '160','cod_uic' => '231','cod_iso' => 'ES','name' => 'MELILLA'],
        ['id' => '161','cod_uic' => '046','cod_iso' => 'MX','name' => 'MESSICO'],
        ['id' => '162','cod_uic' => '215','cod_iso' => 'FM','name' => 'MICRONESIA (STATI FEDERATI DI)'],
        ['id' => '163','cod_uic' => '177','cod_iso' => 'UM','name' => 'MIDWAY ISOLE'],
        ['id' => '164','cod_uic' => '265','cod_iso' => 'MD','name' => 'MOLDAVIA (REPUBBLICA DI)'],
        ['id' => '165','cod_uic' => '110','cod_iso' => 'MN','name' => 'MONGOLIA'],
        ['id' => '166','cod_uic' => '290','cod_iso' => 'ME','name' => 'MONTENEGRO'],
        ['id' => '167','cod_uic' => '208','cod_iso' => 'MS','name' => 'MONTSERRAT'],
        ['id' => '168','cod_uic' => '134','cod_iso' => 'MZ','name' => 'MOZAMBICO'],
        ['id' => '169','cod_uic' => '083','cod_iso' => 'MM','name' => 'MYANMAR'],
        ['id' => '170','cod_uic' => '206','cod_iso' => 'NA','name' => 'NAMIBIA'],
        ['id' => '171','cod_uic' => '109','cod_iso' => 'NR','name' => 'NAURU'],
        ['id' => '172','cod_uic' => '115','cod_iso' => 'NP','name' => 'NEPAL'],
        ['id' => '173','cod_uic' => '047','cod_iso' => 'NI','name' => 'NICARAGUA'],
        ['id' => '174','cod_uic' => '150','cod_iso' => 'NE','name' => 'NIGER'],
        ['id' => '175','cod_uic' => '117','cod_iso' => 'NG','name' => 'NIGERIA'],
        ['id' => '176','cod_uic' => '205','cod_iso' => 'NU','name' => 'NIUE'],
        ['id' => '177','cod_uic' => '285','cod_iso' => 'NF','name' => 'NORFOLK ISOLE'],
        ['id' => '178','cod_uic' => '048','cod_iso' => 'NO','name' => 'NORVEGIA'],
        ['id' => '179','cod_uic' => '253','cod_iso' => 'NC','name' => 'NUOVA CALEDONIA'],
        ['id' => '180','cod_uic' => '049','cod_iso' => 'NZ','name' => 'NUOVA ZELANDA'],
        ['id' => '181','cod_uic' => '163','cod_iso' => 'OM','name' => 'OMAN'],
        ['id' => '182','cod_uic' => '050','cod_iso' => 'NL','name' => 'PAESI BASSI'],
        ['id' => '183','cod_uic' => '036','cod_iso' => 'PK','name' => 'PAKISTAN'],
        ['id' => '184','cod_uic' => '216','cod_iso' => 'PW','name' => 'PALAU'],
        ['id' => '185','cod_uic' => '279','cod_iso' => 'PS','name' => 'PALESTINA, TERRITORI AUTONOMI'],
        ['id' => '186','cod_uic' => '051','cod_iso' => 'PA','name' => 'PANAMA'],
        ['id' => '187','cod_uic' => '186','cod_iso' => 'PG','name' => 'PAPUA NUOVA GUINEA'],
        ['id' => '188','cod_uic' => '052','cod_iso' => 'PY','name' => 'PARAGUAY'],
        ['id' => '189','cod_uic' => '232','cod_iso' => 'ES','name' => 'PENON DE ALHUCEMAS'],
        ['id' => '190','cod_uic' => '233','cod_iso' => 'ES','name' => 'PENON DE VELEZ DE LA GOMERA'],
        ['id' => '191','cod_uic' => '053','cod_iso' => 'PE','name' => 'PERU\''],
        ['id' => '192','cod_uic' => '175','cod_iso' => 'PN','name' => 'PITCAIRN'],
        ['id' => '193','cod_uic' => '225','cod_iso' => 'PF','name' => 'POLINESIA FRANCESE'],
        ['id' => '194','cod_uic' => '054','cod_iso' => 'PL','name' => 'POLONIA'],
        ['id' => '195','cod_uic' => '055','cod_iso' => 'PT','name' => 'PORTOGALLO'],
        ['id' => '196','cod_uic' => '220','cod_iso' => 'PR','name' => 'PORTORICO'],
        ['id' => '197','cod_uic' => '091','cod_iso' => 'MC','name' => 'PRINCIPATO DI MONACO'],
        ['id' => '198','cod_uic' => '168','cod_iso' => 'QA','name' => 'QATAR'],
        ['id' => '199','cod_uic' => '242','cod_iso' => 'AE','name' => 'RAS AL KHAIMAH'],
        ['id' => '200','cod_uic' => '031','cod_iso' => 'GB','name' => 'REGNO UNITO'],
        ['id' => '201','cod_uic' => '247','cod_iso' => 'RE','name' => 'REUNION'],
        ['id' => '202','cod_uic' => '061','cod_iso' => 'RO','name' => 'ROMANIA'],
        ['id' => '203','cod_uic' => '262','cod_iso' => 'RU','name' => 'RUSSIA (FEDERAZIONE DI)'],
        ['id' => '204','cod_uic' => '151','cod_iso' => 'RW','name' => 'RWANDA'],
        ['id' => '205','cod_uic' => '166','cod_iso' => 'EH','name' => 'SAHARA OCCIDENTALE'],
        ['id' => '206','cod_uic' => '293','cod_iso' => 'BL','name' => 'SAINT BARTHELEMY'],
        ['id' => '207','cod_uic' => '222','cod_iso' => 'MF','name' => 'SAINT MARTIN SETTENTRIONALE'],
        ['id' => '208','cod_uic' => '248','cod_iso' => 'PM','name' => 'SAINT-PIERRE E MIQUELON'],
        ['id' => '209','cod_uic' => '191','cod_iso' => 'SB','name' => 'SALOMONE ISOLE'],
        ['id' => '210','cod_uic' => '131','cod_iso' => 'WS','name' => 'SAMOA'],
        ['id' => '211','cod_uic' => '037','cod_iso' => 'SM','name' => 'SAN MARINO'],
        ['id' => '212','cod_uic' => '199','cod_iso' => 'LC','name' => 'SANTA LUCIA'],
        ['id' => '213','cod_uic' => '093','cod_iso' => 'VA','name' => 'CITTA\' DEL VATICANO'],
        ['id' => '214','cod_uic' => '254','cod_iso' => 'SH','name' => 'SANT\'ELENA'],
        ['id' => '215','cod_uic' => '187','cod_iso' => 'ST','name' => 'SAO TOME E PRINCIPE'],
        ['id' => '216','cod_uic' => '152','cod_iso' => 'SN','name' => 'SENEGAL'],
        ['id' => '217','cod_uic' => '289','cod_iso' => 'RS','name' => 'SERBIA'],
        ['id' => '218','cod_uic' => '189','cod_iso' => 'SC','name' => 'SEYCHELLES'],
        ['id' => '219','cod_uic' => '243','cod_iso' => 'AE','name' => 'SHARJAH'],
        ['id' => '220','cod_uic' => '153','cod_iso' => 'SL','name' => 'SIERRA LEONE'],
        ['id' => '221','cod_uic' => '147','cod_iso' => 'SG','name' => 'SINGAPORE'],
        ['id' => '222','cod_uic' => '294','cod_iso' => 'SX','name' => 'SINT MAARTEN (DUTCH PART)'],
        ['id' => '223','cod_uic' => '065','cod_iso' => 'SY','name' => 'SIRIA'],
        ['id' => '224','cod_uic' => '276','cod_iso' => 'SK','name' => 'SLOVACCHIA'],
        ['id' => '225','cod_uic' => '260','cod_iso' => 'SI','name' => 'SLOVENIA'],
        ['id' => '226','cod_uic' => '066','cod_iso' => 'SO','name' => 'SOMALIA'],
        ['id' => '227','cod_uic' => '067','cod_iso' => 'ES','name' => 'SPAGNA'],
        ['id' => '228','cod_uic' => '085','cod_iso' => 'LK','name' => 'SRI LANKA'],
        ['id' => '229','cod_uic' => '196','cod_iso' => 'VC','name' => 'ST. VINCENTE E LE GRENADINE'],
        ['id' => '230','cod_uic' => '069','cod_iso' => 'US','name' => 'STATI UNITI'],
        ['id' => '231','cod_uic' => '195','cod_iso' => 'KN','name' => 'ST.KITTS E NEVIS'],
        ['id' => '232','cod_uic' => '283','cod_iso' => 'GS','name' => 'SUD GEORGIA E SUD SANDWICH'],
        ['id' => '233','cod_uic' => '297','cod_iso' => 'SS','name' => 'SUD SUDAN'],
        ['id' => '234','cod_uic' => '078','cod_iso' => 'ZA','name' => 'SUDAFRICANA (REPUBBLICA)'],
        ['id' => '235','cod_uic' => '070','cod_iso' => 'SD','name' => 'SUDAN'],
        ['id' => '236','cod_uic' => '124','cod_iso' => 'SR','name' => 'SURINAME'],
        ['id' => '237','cod_uic' => '286','cod_iso' => 'SJ','name' => 'SVALBARD E JAN MAYEN ISOLE'],
        ['id' => '238','cod_uic' => '068','cod_iso' => 'SE','name' => 'SVEZIA'],
        ['id' => '239','cod_uic' => '071','cod_iso' => 'CH','name' => 'SVIZZERA'],
        ['id' => '240','cod_uic' => '138','cod_iso' => 'SZ','name' => 'SWAZILAND'],
        ['id' => '241','cod_uic' => '272','cod_iso' => 'TJ','name' => 'TAGIKISTAN'],
        ['id' => '242','cod_uic' => '022','cod_iso' => 'TW','name' => 'TAIWAN'],
        ['id' => '243','cod_uic' => '057','cod_iso' => 'TZ','name' => 'TANZANIA (REPUBBLICA DI)'],
        ['id' => '244','cod_uic' => '183','cod_iso' => 'TF','name' => 'TERRITORI FRANCESI DEL SUD'],
        ['id' => '245','cod_uic' => '245','cod_iso' => 'IO','name' => 'TERRITORIO BRITANNICO OCEANO INDIANO'],
        ['id' => '246','cod_uic' => '072','cod_iso' => 'TH','name' => 'THAILANDIA'],
        ['id' => '247','cod_uic' => '287','cod_iso' => 'TL','name' => 'TIMOR-LESTE'],
        ['id' => '248','cod_uic' => '155','cod_iso' => 'TG','name' => 'TOGO'],
        ['id' => '249','cod_uic' => '236','cod_iso' => 'TK','name' => 'TOKELAU'],
        ['id' => '250','cod_uic' => '162','cod_iso' => 'TO','name' => 'TONGA'],
        ['id' => '251','cod_uic' => '120','cod_iso' => 'TT','name' => 'TRINIDAD E TOBAGO'],
        ['id' => '252','cod_uic' => '229','cod_iso' => 'SH','name' => 'TRISTAN DA CUNHA'],
        ['id' => '253','cod_uic' => '075','cod_iso' => 'TN','name' => 'TUNISIA'],
        ['id' => '254','cod_uic' => '076','cod_iso' => 'TR','name' => 'TURCHIA'],
        ['id' => '255','cod_uic' => '273','cod_iso' => 'TM','name' => 'TURKMENISTAN'],
        ['id' => '256','cod_uic' => '210','cod_iso' => 'TC','name' => 'TURKS E CAICOS ISOLE'],
        ['id' => '257','cod_uic' => '193','cod_iso' => 'TV','name' => 'TUVALU'],
        ['id' => '258','cod_uic' => '263','cod_iso' => 'UA','name' => 'UCRAINA'],
        ['id' => '259','cod_uic' => '132','cod_iso' => 'UG','name' => 'UGANDA'],
        ['id' => '260','cod_uic' => '244','cod_iso' => 'AE','name' => 'UMM AL QAIWAIN'],
        ['id' => '261','cod_uic' => '077','cod_iso' => 'HU','name' => 'UNGHERIA'],
        ['id' => '262','cod_uic' => '080','cod_iso' => 'UY','name' => 'URUGUAY'],
        ['id' => '263','cod_uic' => '271','cod_iso' => 'UZ','name' => 'UZBEKISTAN'],
        ['id' => '264','cod_uic' => '121','cod_iso' => 'VU','name' => 'VANUATU'],
        ['id' => '265','cod_uic' => '081','cod_iso' => 'VE','name' => 'VENEZUELA'],
        ['id' => '266','cod_uic' => '221','cod_iso' => 'VI','name' => 'VERGINI AMERICANE ISOLE'],
        ['id' => '267','cod_uic' => '249','cod_iso' => 'VG','name' => 'VERGINI BRITANNICHE ISOLE'],
        ['id' => '268','cod_uic' => '062','cod_iso' => 'VN','name' => 'VIETNAM'],
        ['id' => '269','cod_uic' => '178','cod_iso' => 'UM','name' => 'WAKE ISOLE'],
        ['id' => '270','cod_uic' => '218','cod_iso' => 'WF','name' => 'WALLIS E FUTUNA ISOLE'],
        ['id' => '271','cod_uic' => '042','cod_iso' => 'YE','name' => 'YEMEN'],
        ['id' => '272','cod_uic' => '058','cod_iso' => 'ZM','name' => 'ZAMBIA'],
        ['id' => '273','cod_uic' => '073','cod_iso' => 'ZW','name' => 'ZIMBABWE'] */
        ['id' => '126','cod_uic' => '086','cod_iso' => 'IT','name' => 'ITALIA'],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('vaance_country')->truncate();
        $final = [];

        foreach (self::$countries as $country) {
            $country['is_active'] = true;
            unset($country['num']);
            unset($country['isd']);
            $country['created_at'] = Carbon::now();

            $final[] = $country;
        }

        DB::table('vaance_country')->insert($final);

        // $this->saveOrUpdate('vaance_country', self::$countries);
    
    }
}
